"""Compliance Engine — SQLAlchemy Models.

Existing models (from initial scaffold):
  - ComplianceSnapshot — per-department daily snapshot (department-centric)
  - NMCStandard — NMC MSR thresholds by intake size (reference table)
  - SAFSubmission — SAF form generation tracking
  - MSRAlert — faculty MSR breach alerts

Compliance framework (C1 — rule-agnostic evaluation):
  - ComplianceStandard — generic compliance rules (Jason populates)
  - ComplianceAlert — alerts generated by the rules engine
  - ComplianceCheckSnapshot — point-in-time full compliance evaluation

SAF Auto-Generation framework (C2 — template-driven):
  - SAFTemplate — form structure definitions (Jason creates)
  - ComplianceDocumentDraft — generated document drafts (tenant-scoped)
"""

import uuid

from sqlalchemy import (
    Boolean,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID

from app.shared.models import Base, TenantModel


class ComplianceSnapshot(TenantModel):
    """Daily compliance score snapshot per department."""
    __tablename__ = "compliance_snapshots"
    __table_args__ = (
        UniqueConstraint("college_id", "department_id", "snapshot_date"),
    )

    department_id = Column(UUID(as_uuid=True), ForeignKey("departments.id"))
    snapshot_date = Column(Date, nullable=False)

    # Faculty MSR
    faculty_required = Column(Integer)
    faculty_actual = Column(Integer)
    faculty_ratio = Column(Float)
    faculty_status = Column(String(10))  # "green", "yellow", "orange", "red"

    # Attendance
    avg_faculty_attendance_pct = Column(Float)
    avg_student_attendance_pct = Column(Float)
    attendance_status = Column(String(10))

    # Hospital Infrastructure
    bed_occupancy_pct = Column(Float)
    opd_daily_avg = Column(Integer)
    ipd_daily_avg = Column(Integer)

    # Overall
    compliance_score = Column(Float)  # 0-100
    risk_level = Column(String(10))   # "low", "medium", "high", "critical"

    # Predictions (Prophet forecasting)
    predicted_score_30d = Column(Float)
    predicted_score_60d = Column(Float)


class NMCStandard(Base):
    """Reference table: NMC MSR thresholds by intake size. NOT tenant-scoped."""
    __tablename__ = "nmc_standards"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    intake_size = Column(Integer, nullable=False)
    department = Column(String(100))

    min_professors = Column(Integer)
    min_associate_professors = Column(Integer)
    min_assistant_professors = Column(Integer)
    min_tutors_demonstrators = Column(Integer)
    min_senior_residents = Column(Integer)

    min_beds = Column(Integer)
    min_opd_per_day = Column(Integer)
    min_lecture_hall_capacity = Column(Integer)
    min_library_books = Column(Integer)
    min_indian_journals = Column(Integer)
    min_foreign_journals = Column(Integer)

    regulation_reference = Column(String(255))
    effective_date = Column(Date)


class SAFSubmission(TenantModel):
    """Tracks SAF form generation and submission status."""
    __tablename__ = "saf_submissions"

    form_type = Column(String(10), nullable=False)  # "AI", "AII", "AIII"
    academic_year = Column(String(10))
    status = Column(String(20), default="draft")

    form_data = Column(JSONB)
    discrepancies = Column(JSONB, default=[])

    generated_at = Column(DateTime(timezone=True))
    generated_by = Column(UUID(as_uuid=True))
    reviewed_by = Column(UUID(as_uuid=True))
    reviewed_at = Column(DateTime(timezone=True))
    submitted_at = Column(DateTime(timezone=True))


class MSRAlert(TenantModel):
    """Faculty MSR strength breach alerts."""
    __tablename__ = "msr_alerts"

    department_id = Column(UUID(as_uuid=True), ForeignKey("departments.id"))
    alert_type = Column(String(50))  # "faculty_shortage", "retirement_upcoming", "ratio_breach"
    severity = Column(String(10))    # "warning", "critical"
    message = Column(Text)
    data = Column(JSONB)
    acknowledged = Column(DateTime(timezone=True))
    resolved = Column(DateTime(timezone=True))


# ---------------------------------------------------------------------------
# New models — Rule-agnostic compliance framework
# ---------------------------------------------------------------------------


class ComplianceStandard(Base):
    """Generic compliance standard. NOT tenant-scoped — rules are universal.

    Jason populates this table with NMC/NAAC/NBA rules after his audit.
    The ComplianceRulesEngine loads these and evaluates them against
    current data for each college.

    Works with zero rules (returns "no standards configured") and with
    500+ rules (no code changes needed). Every threshold, code, and
    severity mapping lives here, never hardcoded in Python.
    """
    __tablename__ = "compliance_standards"
    __table_args__ = (
        Index("ix_cs_category_active", "category", "is_active"),
        Index("ix_cs_regulatory_active", "regulatory_body", "is_active"),
    )

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Identity
    standard_code = Column(
        String(50), unique=True, nullable=False,
        comment="Unique code e.g. MSR.3.2.1 — Jason defines these",
    )
    category = Column(
        String(50), nullable=False,
        comment="attendance, faculty, infrastructure, etc.",
    )
    subcategory = Column(
        String(50), nullable=True,
        comment="student_attendance, faculty_qualification, etc.",
    )
    title = Column(String(500), nullable=False)
    description = Column(Text, nullable=False)

    # Data source configuration — what to query
    data_source = Column(
        String(100), nullable=False,
        comment="Registered data fetcher name: attendance_records, faculty_roster, etc.",
    )
    data_query_config = Column(
        JSONB, nullable=False,
        comment='{"source": "...", "metric": "percentage", "aggregation": "avg", '
                '"group_by": "department", "time_window_days": 30}',
    )

    # Threshold — what to compare against
    threshold_type = Column(
        String(30), nullable=False,
        comment="min_percentage, min_count, max_count, min_ratio, boolean, custom",
    )
    threshold_value = Column(
        String(100), nullable=False,
        comment='e.g. "75", "1:3", "true"',
    )
    comparison_operator = Column(
        String(5), nullable=False, server_default="gte",
        comment="gte, lte, eq, gt, lt",
    )
    buffer_warning_pct = Column(
        Float, nullable=False, server_default=text("10.0"),
        comment="How close to threshold triggers warning (percentage)",
    )

    # Severity and regulation
    severity_if_breached = Column(
        String(30), nullable=False,
        comment="informational, warning, show_cause, seat_reduction, closure_risk",
    )
    regulatory_body = Column(
        String(20), nullable=False,
        comment="nmc, naac, nba, university, internal",
    )
    source_document = Column(
        String(500), nullable=True,
        comment="Reference to regulation document",
    )

    # Lifecycle
    effective_from = Column(Date, nullable=True)
    effective_until = Column(
        Date, nullable=True,
        comment="For rules that change between academic years",
    )
    is_active = Column(Boolean, nullable=False, server_default="true")
    priority = Column(
        Integer, nullable=False, server_default=text("5"),
        comment="1=highest priority for display ordering",
    )

    # Audit
    created_at = Column(
        DateTime(timezone=True),
        server_default=text("NOW()"),
        nullable=False,
    )
    updated_at = Column(
        DateTime(timezone=True),
        server_default=text("NOW()"),
        nullable=False,
    )
    created_by = Column(
        UUID(as_uuid=True), nullable=True,
        comment="Jason's user_id when he enters rules",
    )


class ComplianceAlert(TenantModel):
    """Compliance alert generated by the rules engine.

    Created when a standard is found non-compliant or at risk.
    Lifecycle: active → acknowledged → in_progress → resolved
    (or escalated if not resolved by auto_escalation_date).
    """
    __tablename__ = "compliance_alerts"
    __table_args__ = (
        Index(
            "ix_ca_college_severity_status",
            "college_id", "severity", "status",
        ),
        Index(
            "ix_ca_college_standard_status",
            "college_id", "standard_id", "status",
        ),
        Index(
            "ix_ca_college_created",
            "college_id", "created_at",
            postgresql_using="btree",
        ),
    )

    # Links
    execution_id = Column(
        UUID(as_uuid=True),
        ForeignKey("agent_executions.id"),
        nullable=True,
        comment="AgentExecution that generated this alert",
    )
    standard_id = Column(
        UUID(as_uuid=True),
        ForeignKey("compliance_standards.id"),
        nullable=True,
        comment="Null for system-generated alerts",
    )

    # Alert content
    severity = Column(
        String(10), nullable=False,
        comment="green, yellow, orange, red",
    )
    category = Column(String(50), nullable=False)
    title = Column(String(500), nullable=False)
    details = Column(Text, nullable=False)
    current_value = Column(
        String(100), nullable=True,
        comment="What the actual data shows",
    )
    threshold_value = Column(
        String(100), nullable=True,
        comment="What the standard requires",
    )
    gap_description = Column(
        String(500), nullable=True,
        comment="Human-readable gap explanation",
    )
    recommended_action = Column(Text, nullable=True)

    # Deadlines
    deadline = Column(Date, nullable=True)
    auto_escalation_date = Column(
        Date, nullable=True,
        comment="If not resolved by this date, auto-escalate",
    )

    # Status tracking
    status = Column(
        String(20), nullable=False, server_default="active",
        comment="active, acknowledged, in_progress, resolved, escalated, dismissed",
    )
    acknowledged_by = Column(UUID(as_uuid=True), nullable=True)
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)
    resolved_by = Column(UUID(as_uuid=True), nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    resolution_notes = Column(Text, nullable=True)


class ComplianceCheckSnapshot(TenantModel):
    """Point-in-time snapshot of a full compliance evaluation.

    Named ComplianceCheckSnapshot (not ComplianceSnapshot) to avoid
    collision with the existing per-department ComplianceSnapshot model.

    Created by the compliance engine on each evaluation run.
    check_results stores per-standard results as JSONB.
    data_gaps tracks standards that couldn't be evaluated (missing data).
    """
    __tablename__ = "compliance_check_snapshots"
    __table_args__ = (
        UniqueConstraint(
            "college_id", "snapshot_date", "snapshot_type",
            name="uq_compliance_check_snapshot",
        ),
    )

    snapshot_date = Column(Date, nullable=False)
    snapshot_type = Column(
        String(20), nullable=False,
        comment="daily_auto, manual, monthly_report, pre_inspection",
    )
    overall_status = Column(
        String(10), nullable=False,
        comment="green, yellow, orange, red",
    )

    # Summary counts
    standards_checked = Column(Integer, nullable=False, server_default=text("0"))
    standards_compliant = Column(Integer, nullable=False, server_default=text("0"))
    standards_at_risk = Column(Integer, nullable=False, server_default=text("0"))
    standards_breached = Column(Integer, nullable=False, server_default=text("0"))

    # Detailed results
    department_statuses = Column(
        JSONB, nullable=True,
        comment='{"dept_name": {"status": "green", "issues": []}}',
    )
    check_results = Column(
        JSONB, nullable=True,
        comment="Full per-standard evaluation results",
    )
    data_gaps = Column(
        JSONB, nullable=True,
        comment="Standards that couldn't be checked (missing data sources)",
    )

    # Approval
    approved_by = Column(UUID(as_uuid=True), nullable=True)
    approved_at = Column(DateTime(timezone=True), nullable=True)


# ---------------------------------------------------------------------------
# SAF Auto-Generation framework (C2) — template-driven document generation
# ---------------------------------------------------------------------------


class SAFTemplate(Base):
    """Form template definition. NOT tenant-scoped — templates are platform-wide.

    Jason creates these after his NMC/NAAC/NBA audit. Each template defines
    the complete structure of a compliance form (sections, fields, data
    mappings). The SAFGenerator loads a template and fills it with data.

    Form-specific details (section names, field names, structures) live
    entirely in the ``sections`` JSONB column — NEVER hardcoded in Python.
    """
    __tablename__ = "saf_templates"
    __table_args__ = (
        Index("ix_saf_tpl_body_active", "regulatory_body", "is_active"),
    )

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    template_code = Column(
        String(50), unique=True, nullable=False,
        comment="Unique code e.g. NMC_SAF_AI, NAAC_SSR, NBA_SAR",
    )
    title = Column(String(500), nullable=False)
    description = Column(Text, nullable=True)
    regulatory_body = Column(
        String(20), nullable=False,
        comment="nmc, naac, nba, university, internal",
    )
    version = Column(Integer, nullable=False, server_default=text("1"))

    sections = Column(
        JSONB, nullable=False,
        comment=(
            'Array of section defs: [{"section_code": "A1", "title": "...", '
            '"order": 1, "fields": [{"field_code": "A1.1", "label": "...", '
            '"field_type": "text|number|table|narrative|date", '
            '"data_source": "...|null", "data_query_config": {...}, '
            '"is_required": true, "requires_narrative": false, '
            '"narrative_prompt": "...|null", "validation_rules": {...}, '
            '"help_text": "..."}]}]'
        ),
    )

    is_active = Column(Boolean, nullable=False, server_default="true")
    created_by = Column(UUID(as_uuid=True), nullable=True)
    created_at = Column(
        DateTime(timezone=True),
        server_default=text("NOW()"),
        nullable=False,
    )
    updated_at = Column(
        DateTime(timezone=True),
        server_default=text("NOW()"),
        nullable=False,
    )


class ComplianceDocumentDraft(TenantModel):
    """Generated compliance document draft. Tenant-scoped.

    Created by SAFGenerator when a compliance officer requests document
    generation from a template. Tracks the full lifecycle from generation
    through review to submission.

    Lifecycle: generating → draft → in_review → approved → submitted
    """
    __tablename__ = "compliance_document_drafts"
    __table_args__ = (
        Index(
            "ix_cdd_college_template_status",
            "college_id", "template_id", "status",
        ),
    )

    template_id = Column(
        UUID(as_uuid=True),
        ForeignKey("saf_templates.id"),
        nullable=False,
        comment="Which template was used to generate this document",
    )
    academic_year = Column(
        String(20), nullable=True,
        comment="e.g. 2025-2026",
    )
    status = Column(
        String(20), nullable=False, server_default="generating",
        comment="generating, draft, in_review, approved, submitted",
    )

    filled_data = Column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb"),
        comment="All auto-filled + manually entered data keyed by field_code",
    )
    data_gaps = Column(
        JSONB, nullable=True,
        comment="List of fields needing manual entry",
    )
    auto_fill_percentage = Column(
        Float, nullable=True,
        comment="How much was auto-filled vs manual (0-100)",
    )
    narrative_sections = Column(
        JSONB, nullable=True,
        comment="AI-generated narrative text keyed by field_code",
    )
    review_comments = Column(JSONB, nullable=True)

    generated_by = Column(UUID(as_uuid=True), nullable=False)
    generated_at = Column(DateTime(timezone=True), nullable=True)
    approved_by = Column(UUID(as_uuid=True), nullable=True)
    approved_at = Column(DateTime(timezone=True), nullable=True)
    submitted_at = Column(DateTime(timezone=True), nullable=True)

    execution_id = Column(
        UUID(as_uuid=True),
        ForeignKey("agent_executions.id"),
        nullable=True,
        comment="AgentExecution that generated this draft",
    )
