"""recommendation_engine

Revision ID: d4e5f6a7b8c9
Revises: c3d4e5f6a7b8
Create Date: 2026-02-11 23:30:00.000000

Creates tables for the S6 Recommendation Engine:

student_recommendations:
  - Persisted recommendations with lifecycle tracking
  - Tenant-scoped with RLS

student_study_plans:
  - Weekly study plans generated by S6
  - Tenant-scoped with RLS
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd4e5f6a7b8c9'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # 1. student_recommendations
    # ------------------------------------------------------------------
    op.create_table(
        'student_recommendations',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('college_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('student_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('execution_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('type', sa.String(length=30), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('action', sa.String(length=500), nullable=False),
        sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('deep_link', sa.String(length=500), nullable=True),
        sa.Column('trigger', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
        sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('dismiss_reason', sa.Text(), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completion_feedback', sa.Text(), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['college_id'], ['colleges.id']),
        sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.id']),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_index(
        'ix_student_rec_student_status',
        'student_recommendations',
        ['college_id', 'student_id', 'status'],
        unique=False,
    )
    op.create_index(
        'ix_student_rec_student_created',
        'student_recommendations',
        ['college_id', 'student_id', 'created_at'],
        unique=False,
    )

    # ------------------------------------------------------------------
    # 2. student_study_plans
    # ------------------------------------------------------------------
    op.create_table(
        'student_study_plans',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('college_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('student_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('execution_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('week_start', sa.Date(), nullable=False),
        sa.Column('week_end', sa.Date(), nullable=False),
        sa.Column('plan_data', postgresql.JSONB(), nullable=False),
        sa.Column('focus_subjects', postgresql.JSONB(), nullable=True),
        sa.Column('weekly_goal', sa.String(length=500), nullable=True),
        sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
        sa.ForeignKeyConstraint(['college_id'], ['colleges.id']),
        sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.id']),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_index(
        'ix_student_plan_student_status',
        'student_study_plans',
        ['college_id', 'student_id', 'status'],
        unique=False,
    )

    # ------------------------------------------------------------------
    # 3. RLS policies for both tables
    # ------------------------------------------------------------------
    for table in ('student_recommendations', 'student_study_plans'):
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY')
        op.execute(
            f"CREATE POLICY tenant_isolation_policy ON {table} "
            f"USING (college_id = NULLIF(current_setting('app.current_college_id', true), '')::uuid)"
        )
        op.execute(
            f"CREATE POLICY superadmin_bypass_policy ON {table} "
            f"USING (current_setting('app.is_superadmin', true) = 'true')"
        )


def downgrade() -> None:
    # Drop RLS policies
    for table in ('student_study_plans', 'student_recommendations'):
        op.execute(f'DROP POLICY IF EXISTS superadmin_bypass_policy ON {table}')
        op.execute(f'DROP POLICY IF EXISTS tenant_isolation_policy ON {table}')

    # Drop indexes
    op.drop_index('ix_student_plan_student_status', table_name='student_study_plans')
    op.drop_index('ix_student_rec_student_created', table_name='student_recommendations')
    op.drop_index('ix_student_rec_student_status', table_name='student_recommendations')

    # Drop tables
    op.drop_table('student_study_plans')
    op.drop_table('student_recommendations')
