"""initial_schema

Revision ID: e9e6bad15ab6
Revises: 
Create Date: 2026-02-09 20:42:11.239252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9e6bad15ab6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('university_affiliation', sa.String(length=255), nullable=True),
    sa.Column('nmc_recognition_status', sa.String(length=50), nullable=True),
    sa.Column('total_intake', sa.Integer(), nullable=False),
    sa.Column('intake_year_started', sa.Integer(), nullable=True),
    sa.Column('required_faculty', sa.Integer(), nullable=True),
    sa.Column('required_tutors', sa.Integer(), nullable=True),
    sa.Column('required_beds', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='NOW()', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('competencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=5), nullable=False),
    sa.Column('is_certifiable', sa.Boolean(), nullable=True),
    sa.Column('min_performances', sa.Integer(), nullable=True),
    sa.Column('blooms_level', sa.String(length=20), nullable=True),
    sa.Column('domain', sa.String(length=20), nullable=True),
    sa.Column('horizontal_integrations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vertical_integrations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mbbs_phase', sa.String(length=10), nullable=True),
    sa.Column('is_aetcom', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('nmc_standards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intake_size', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('min_professors', sa.Integer(), nullable=True),
    sa.Column('min_associate_professors', sa.Integer(), nullable=True),
    sa.Column('min_assistant_professors', sa.Integer(), nullable=True),
    sa.Column('min_tutors_demonstrators', sa.Integer(), nullable=True),
    sa.Column('min_senior_residents', sa.Integer(), nullable=True),
    sa.Column('min_beds', sa.Integer(), nullable=True),
    sa.Column('min_opd_per_day', sa.Integer(), nullable=True),
    sa.Column('min_lecture_hall_capacity', sa.Integer(), nullable=True),
    sa.Column('min_library_books', sa.Integer(), nullable=True),
    sa.Column('min_indian_journals', sa.Integer(), nullable=True),
    sa.Column('min_foreign_journals', sa.Integer(), nullable=True),
    sa.Column('regulation_reference', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_college_id'), 'audit_log', ['college_id'], unique=False)
    op.create_table('batches',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=10), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_college_id'), 'batches', ['college_id'], unique=False)
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('department_type', sa.String(length=20), nullable=True),
    sa.Column('hod_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['hod_id'], ['faculty.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_college_id'), 'departments', ['college_id'], unique=False)
    op.create_table('fee_structures',
    sa.Column('academic_year', sa.String(length=10), nullable=False),
    sa.Column('quota', sa.String(length=30), nullable=False),
    sa.Column('tuition_fee', sa.BigInteger(), nullable=False),
    sa.Column('development_fee', sa.BigInteger(), nullable=True),
    sa.Column('hostel_fee', sa.BigInteger(), nullable=True),
    sa.Column('mess_fee', sa.BigInteger(), nullable=True),
    sa.Column('exam_fee', sa.BigInteger(), nullable=True),
    sa.Column('library_fee', sa.BigInteger(), nullable=True),
    sa.Column('lab_fee', sa.BigInteger(), nullable=True),
    sa.Column('caution_deposit', sa.BigInteger(), nullable=True),
    sa.Column('admission_charges', sa.BigInteger(), nullable=True),
    sa.Column('fee_regulatory_cap', sa.BigInteger(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_structures_college_id'), 'fee_structures', ['college_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('razorpay_event_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_event_id')
    )
    op.create_index(op.f('ix_payment_transactions_college_id'), 'payment_transactions', ['college_id'], unique=False)
    op.create_table('question_bank_items',
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('organ_system', sa.String(length=100), nullable=True),
    sa.Column('blooms_level', sa.String(length=20), nullable=False),
    sa.Column('difficulty_rating', sa.Integer(), nullable=True),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('lead_in', sa.Text(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('difficulty_index', sa.Float(), nullable=True),
    sa.Column('discrimination_index', sa.Float(), nullable=True),
    sa.Column('point_biserial', sa.Float(), nullable=True),
    sa.Column('non_functional_distractors', sa.Integer(), nullable=True),
    sa.Column('is_aetcom', sa.Boolean(), nullable=True),
    sa.Column('nmc_compliant', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bank_items_college_id'), 'question_bank_items', ['college_id'], unique=False)
    op.create_table('saf_submissions',
    sa.Column('form_type', sa.String(length=10), nullable=False),
    sa.Column('academic_year', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discrepancies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saf_submissions_college_id'), 'saf_submissions', ['college_id'], unique=False)
    op.create_table('students',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('aadhaar_hash', sa.String(length=64), nullable=True),
    sa.Column('neet_roll_number', sa.String(length=20), nullable=True),
    sa.Column('neet_score', sa.Integer(), nullable=True),
    sa.Column('neet_rank', sa.Integer(), nullable=True),
    sa.Column('neet_percentile', sa.Float(), nullable=True),
    sa.Column('admission_quota', sa.String(length=30), nullable=True),
    sa.Column('admission_year', sa.Integer(), nullable=True),
    sa.Column('current_phase', sa.String(length=10), nullable=True),
    sa.Column('current_semester', sa.Integer(), nullable=True),
    sa.Column('enrollment_number', sa.String(length=50), nullable=True),
    sa.Column('university_registration_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    op.create_index(op.f('ix_students_college_id'), 'students', ['college_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('person_type', sa.String(length=10), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hours_present', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('within_geofence', sa.String(length=5), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_college_id'), 'attendance_records', ['college_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_college_id'), 'chat_sessions', ['college_id'], unique=False)
    op.create_table('compliance_snapshots',
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('faculty_required', sa.Integer(), nullable=True),
    sa.Column('faculty_actual', sa.Integer(), nullable=True),
    sa.Column('faculty_ratio', sa.Float(), nullable=True),
    sa.Column('faculty_status', sa.String(length=10), nullable=True),
    sa.Column('avg_faculty_attendance_pct', sa.Float(), nullable=True),
    sa.Column('avg_student_attendance_pct', sa.Float(), nullable=True),
    sa.Column('attendance_status', sa.String(length=10), nullable=True),
    sa.Column('bed_occupancy_pct', sa.Float(), nullable=True),
    sa.Column('opd_daily_avg', sa.Integer(), nullable=True),
    sa.Column('ipd_daily_avg', sa.Integer(), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('predicted_score_30d', sa.Float(), nullable=True),
    sa.Column('predicted_score_60d', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'department_id', 'snapshot_date')
    )
    op.create_index(op.f('ix_compliance_snapshots_college_id'), 'compliance_snapshots', ['college_id'], unique=False)
    op.create_table('faculty',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('nmc_faculty_id', sa.String(length=50), nullable=True),
    sa.Column('aebas_id', sa.String(length=50), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('retirement_date', sa.Date(), nullable=True),
    sa.Column('teaching_experience_years', sa.Float(), nullable=True),
    sa.Column('clinical_experience_years', sa.Float(), nullable=True),
    sa.Column('qualification_validated', sa.Boolean(), nullable=True),
    sa.Column('is_eligible_per_nmc', sa.Boolean(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=True),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    op.create_index(op.f('ix_faculty_college_id'), 'faculty', ['college_id'], unique=False)
    op.create_table('fee_payments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('fee_structure_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('fee_component', sa.String(length=50), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('installment_number', sa.Integer(), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index(op.f('ix_fee_payments_college_id'), 'fee_payments', ['college_id'], unique=False)
    op.create_table('flashcards',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('competency_code', sa.String(length=20), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_college_id'), 'flashcards', ['college_id'], unique=False)
    op.create_table('hmis_data_points',
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hmis_data_points_college_id'), 'hmis_data_points', ['college_id'], unique=False)
    op.create_table('msr_alerts',
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('acknowledged', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_msr_alerts_college_id'), 'msr_alerts', ['college_id'], unique=False)
    op.create_table('pdf_annotations',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('document_key', sa.String(length=500), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('annotation_type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_offline', sa.Boolean(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_annotations_college_id'), 'pdf_annotations', ['college_id'], unique=False)
    op.create_table('practice_tests',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_tests_college_id'), 'practice_tests', ['college_id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_college_id'), 'study_sessions', ['college_id'], unique=False)
    op.create_table('assessments',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('assessment_type', sa.String(length=30), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('blueprint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('conducted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_college_id'), 'assessments', ['college_id'], unique=False)
    op.create_table('clinical_rotations',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('required_hours', sa.Integer(), nullable=True),
    sa.Column('completed_hours', sa.Integer(), nullable=True),
    sa.Column('posting_assessment_score', sa.Float(), nullable=True),
    sa.Column('assessed_by', sa.UUID(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_rotations_college_id'), 'clinical_rotations', ['college_id'], unique=False)
    op.create_table('flashcard_reviews',
    sa.Column('flashcard_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('interval_days', sa.Float(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_reviews_college_id'), 'flashcard_reviews', ['college_id'], unique=False)
    op.create_table('lesson_plans',
    sa.Column('faculty_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('competency_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('teaching_hours', sa.Integer(), nullable=True),
    sa.Column('blooms_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('teaching_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('learning_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assessment_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('integration_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_plans_college_id'), 'lesson_plans', ['college_id'], unique=False)
    op.create_table('logbook_entries',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=True),
    sa.Column('performance_count', sa.Integer(), nullable=True),
    sa.Column('clinical_setting', sa.String(length=100), nullable=True),
    sa.Column('patient_consent_obtained', sa.Boolean(), nullable=True),
    sa.Column('evidence_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_method', sa.String(length=20), nullable=True),
    sa.Column('created_offline', sa.Boolean(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logbook_entries_college_id'), 'logbook_entries', ['college_id'], unique=False)
    op.create_table('test_attempts',
    sa.Column('practice_test_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('time_taken_minutes', sa.Integer(), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['practice_test_id'], ['practice_tests.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_attempts_college_id'), 'test_attempts', ['college_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_attempts_college_id'), table_name='test_attempts')
    op.drop_table('test_attempts')
    op.drop_index(op.f('ix_logbook_entries_college_id'), table_name='logbook_entries')
    op.drop_table('logbook_entries')
    op.drop_index(op.f('ix_lesson_plans_college_id'), table_name='lesson_plans')
    op.drop_table('lesson_plans')
    op.drop_index(op.f('ix_flashcard_reviews_college_id'), table_name='flashcard_reviews')
    op.drop_table('flashcard_reviews')
    op.drop_index(op.f('ix_clinical_rotations_college_id'), table_name='clinical_rotations')
    op.drop_table('clinical_rotations')
    op.drop_index(op.f('ix_assessments_college_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_study_sessions_college_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_practice_tests_college_id'), table_name='practice_tests')
    op.drop_table('practice_tests')
    op.drop_index(op.f('ix_pdf_annotations_college_id'), table_name='pdf_annotations')
    op.drop_table('pdf_annotations')
    op.drop_index(op.f('ix_msr_alerts_college_id'), table_name='msr_alerts')
    op.drop_table('msr_alerts')
    op.drop_index(op.f('ix_hmis_data_points_college_id'), table_name='hmis_data_points')
    op.drop_table('hmis_data_points')
    op.drop_index(op.f('ix_flashcards_college_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_fee_payments_college_id'), table_name='fee_payments')
    op.drop_table('fee_payments')
    op.drop_index(op.f('ix_faculty_college_id'), table_name='faculty')
    op.drop_table('faculty')
    op.drop_index(op.f('ix_compliance_snapshots_college_id'), table_name='compliance_snapshots')
    op.drop_table('compliance_snapshots')
    op.drop_index(op.f('ix_chat_sessions_college_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_attendance_records_college_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_students_college_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_saf_submissions_college_id'), table_name='saf_submissions')
    op.drop_table('saf_submissions')
    op.drop_index(op.f('ix_question_bank_items_college_id'), table_name='question_bank_items')
    op.drop_table('question_bank_items')
    op.drop_index(op.f('ix_payment_transactions_college_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_fee_structures_college_id'), table_name='fee_structures')
    op.drop_table('fee_structures')
    op.drop_index(op.f('ix_departments_college_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_batches_college_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_audit_log_college_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('nmc_standards')
    op.drop_table('competencies')
    op.drop_table('colleges')
    # ### end Alembic commands ###
